import { PublishFilter } from './parse-publish-config'
import { join } from 'node:path'
import { log, note } from '@clack/prompts'
import { writeFile } from 'node:fs/promises'

export async function generatePublishFiltersTs({
  output,
  filters,
  verbose,
}: {
  output: string
  filters: PublishFilter[]
  verbose: boolean
}) {
  const target = join(output, 'filters.ts')
  log.step(`Writing filters.ts${verbose ? ` to ${target}` : ''}`)
  if (verbose) {
    note(`filters: ${JSON.stringify(filters, undefined, 2)}`)
  }
  await writeFile(
    target,
    [
      `// Generated by repokit publish`,
      `import { RepokitFilter } from './types'`,
      `export const filters: RepokitFilter[] = ${JSON.stringify(filters, undefined, 2)}`,
    ].join('\n\n'),
  )
}
