import { PublishSource } from './parse-publish-config'
import { join } from 'node:path'
import { log, note } from '@clack/prompts'
import { writeFile } from 'node:fs/promises'

export async function generatePublishSourcesTs({
  output,
  sources,
  verbose,
}: {
  output: string
  sources: PublishSource[]
  verbose: boolean
}) {
  const target = join(output, 'sources.ts')
  log.step(`Writing sources.ts${verbose ? ` to ${target}` : ''}`)
  if (verbose) {
    note(`sources: ${JSON.stringify(sources, undefined, 2)}`)
  }
  await writeFile(
    target,
    [
      `// Generated by repokit publish`,
      `import { RepokitSource } from './types'`,
      `export const sources: RepokitSource[] = ${JSON.stringify(sources, undefined, 2)}`,
    ].join('\n\n'),
  )
}
