import { PublishTemplate } from './convert-publish-template'
import { join } from 'node:path'
import { writeFile } from 'node:fs/promises'
import { log, note } from '@clack/prompts'

export async function generatePublishTemplatesTs({
  output,
  templates,
  verbose,
}: {
  output: string
  templates: PublishTemplate[]
  verbose: boolean
}) {
  const target = join(output, 'templates.ts')
  log.step(`Writing templates.ts${verbose ? ` to ${target}` : ''}`)
  if (verbose) {
    note(
      `templates: ${JSON.stringify(
        templates.map((t) => t.id),
        undefined,
        2,
      )}`,
    )
  }
  await writeFile(
    target,
    [
      `// Generated by repokit publish`,
      `import { RepokitTemplate } from './types'`,
      `export const templates: RepokitTemplate[] = ${JSON.stringify(templates, undefined, 2)}`,
    ].join('\n\n'),
  )
}
