import { log, note } from '@clack/prompts'
import { ensurePublishConfig } from './ensure-publish-config'
import { PublishTemplate } from './convert-publish-template'
import { getTemplatesForSources } from './get-templates-for-sources'
import { join } from 'node:path'
import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { execPrettier } from './exec-prettier'
import sharp from 'sharp'
import { generatePublishTypes } from './generate-publish-types'

export async function runCommandPublish(options: { config: string; format: boolean; verbose: boolean }) {
  const path = process.cwd()
  const config = ensurePublishConfig({ path, ...options })

  if (options.verbose) {
    note(JSON.stringify(config, undefined, 2))
  }
  const output = join(path, config.output)
  if (!existsSync(output)) {
    await mkdir(output, { recursive: true })
    log.info(`Created output directory: ${output}`)
  }
  if (options.verbose) {
    log.info(`Writing metadata to ${output}`)
  }

  try {
    const templates: PublishTemplate[] = await getTemplatesForSources({
      sources: config.sources,
      verbose: options.verbose,
    })
    const json = JSON.stringify(templates, undefined, 2) + '\n'

    // Write the filters.ts file to the output directory
    const filtersTsPath = join(output, 'filters.ts')
    await writeFile(
      filtersTsPath,
      [
        `// Generated by repokit publish`,
        `import { RepokitFilter } from './types'`,
        `export const filters: RepokitFilter[] = ${JSON.stringify(config.filters, undefined, 2)}`,
      ].join('\n\n'),
    )

    // Write the templates.ts file to the output directory
    const templatesTsPath = join(output, 'templates.ts')
    await writeFile(
      templatesTsPath,
      [
        `// Generated by repokit publish`,
        `import { RepokitTemplate } from './types'`,
        `export const templates: RepokitTemplate[] = ${json}`,
      ].join('\n\n'),
    )
    log.info(`Published typescript ${options.verbose ? `to: ${templatesTsPath}` : ''}`)

    const typesPath = join(output, 'types.ts')
    await writeFile(typesPath, generatePublishTypes())
    log.info(`Published types ${options.verbose ? `to: ${typesPath}` : ''}`)

    if (options.format) {
      execPrettier({ files: '.', path: output, verbose: options.verbose })
    }
    log.info(`Generating images`)
    for (const template of templates) {
      await generateImage({ template, target: join(output, 'images'), verbose: options.verbose })
    }
  } catch (error) {
    throw new Error(`Error publishing metadata: ${error}`)
  }
}

function getStyle() {
  return {
    background: '#000000',
    foreground: '#ffffff',
    gradientStart: '#9945FF',
    gradientEnd: '#14F195',
    tagColor: '#888888',
    fontFamily: 'SF Pro, Inter, system-ui, sans-serif',
    titleFontSize: 120,
    descriptionFontSize: 60,
    tagFontSize: 40,
  }
}

function generateTemplateSvg(template: PublishTemplate) {
  const style = getStyle()
  const width = 2400
  const height = 1260

  // A simple text wrapper
  function wrapText(text: string, lineLength: number): string[] {
    const words = text.split(' ')
    if (words.length === 0) return []
    const lines: string[] = []
    let currentLine = words[0]

    for (let i = 1; i < words.length; i++) {
      if (currentLine.length + words[i].length + 1 <= lineLength) {
        currentLine += ' ' + words[i]
      } else {
        lines.push(currentLine)
        currentLine = words[i]
      }
    }
    lines.push(currentLine)
    return lines
  }

  const descriptionLines = wrapText(template.description, 40)
  const descriptionTspans = descriptionLines
    .map((line) => `<tspan x="${width / 2}" dy="1.2em">${line}</tspan>`)
    .join('')

  const tags = template.keywords?.join('  ·  ')

  return `
    <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="titleGradient" x1="0%" y1="0%" x2="100%" y2="0%">
          <stop offset="0%" stop-color="${style.gradientStart}" />
          <stop offset="100%" stop-color="${style.gradientEnd}" />
        </linearGradient>
      </defs>
      <rect width="100%" height="100%" fill="${style.background}" />
      <text
        x="${width / 2}"
        y="450"
        font-family="${style.fontFamily}"
        font-size="${style.titleFontSize}"
        font-weight="bold"
        fill="url(#titleGradient)"
        text-anchor="middle"
      >
        ${template.name}
      </text>
      <text
        y="580"
        font-family="${style.fontFamily}"
        font-size="${style.descriptionFontSize}"
        fill="${style.foreground}"
        text-anchor="middle"
      >
        ${descriptionTspans}
      </text>
      <text
        x="${width / 2}"
        y="850"
        font-family="${style.fontFamily}"
        font-size="${style.tagFontSize}"
        fill="${style.tagColor}"
        text-anchor="middle"
      >
        ${tags}
      </text>
    </svg>
  `
}

async function generateImage({
  template,
  target,
  verbose,
}: {
  template: PublishTemplate
  target: string
  verbose: boolean
}) {
  if (!existsSync(target)) {
    log.warn(`Creating directory: ${target}`)
    await mkdir(target, { recursive: true })
  }
  const svg = generateTemplateSvg(template)
  const baseName = `${target}/${template.source.name}-${template.name}-preview`
  if (verbose) {
    log.info(`Generating image for ${baseName}`)
  }
  await writeFile(`${baseName}.svg`, svg)
  await sharp(Buffer.from(svg)).png().toFile(`${baseName}.png`)
}

export async function generatePublishOutput({
  //
  output,
}: {
  output: string
}) {
  console.log('publish output', output)
}
